# Generated by Django 3.2.8 on 2021-10-20 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import src.car_showroom.models
import src.tools.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_showroom', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=14)),
                ('balance', src.tools.fields.DecimalRangeField(decimal_places=2, max_digits=10, null=True)),
                ('sample', models.JSONField(blank=True, default=src.car_showroom.models.jsonfield_default_value)),
                ('country', django_countries.fields.CountryField(blank=True, default=None, max_length=2)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name', 'balance', 'country'),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.car', to_field='vin')),
                ('car_showroom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='car_showroom.carshowroom')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='cars',
            field=models.ManyToManyField(through='customer.Purchase', to='supplier.Car'),
        ),
    ]
