# Generated by Django 3.2.8 on 2021-10-13 08:06

from django.db import migrations
import src.tools.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=src.tools.fields.DecimalRangeField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
