# Generated by Django 3.2.8 on 2021-10-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0002_alter_carshowroom_description'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name', 'balance', 'country')},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='car_showroom',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='car_showroom.carshowroom'),
        ),
    ]
