# Generated by Django 3.2.8 on 2021-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
