# Generated by Django 3.2.8 on 2021-10-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0002_alter_supplier_car_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Car_showroom_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.car', to_field='vin')),
                ('сar_showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_showroom.car_showroom')),
            ],
        ),
        migrations.AddField(
            model_name='car_showroom',
            name='car',
            field=models.ManyToManyField(through='car_showroom.Car_showroom_Car', to='supplier.Car'),
        ),
    ]
