# Generated by Django 3.2.8 on 2021-10-28 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import src.car_showroom.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sortquery', models.JSONField(blank=True, default=src.car_showroom.models.jsonfield_default_value)),
                ('country', django_countries.fields.CountryField(blank=True, default=None, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarsOfShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=1)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_of_showroom', related_query_name='car_of_showroom', to='supplier.car', to_field='vin')),
                ('сar_showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showrooms', related_query_name='showroom', to='car_showroom.carshowroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='cars',
            field=models.ManyToManyField(through='car_showroom.CarsOfShowroom', to='supplier.Car'),
        ),
    ]
