# Generated by Django 3.2.8 on 2021-11-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('car_showroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshowroom',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.location'),
        ),
    ]
