# Generated by Django 3.2.8 on 2021-10-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_showroom',
            name='sortquery',
            field=models.JSONField(blank=True, default=None),
        ),
    ]
