# Generated by Django 3.2.8 on 2021-10-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowroom',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
