# Generated by Django 3.2.8 on 2021-10-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0002_alter_carshowroom_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsofshowroom',
            old_name='сarShowroom',
            new_name='сar_showroom',
        ),
    ]
