# Generated by Django 3.2.8 on 2021-11-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20211112_0905'),
        ('car_showroom', '0002_carshowroom_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsofshowroom',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', related_query_name='supplier', to='supplier.supplier'),
        ),
    ]
