# Generated by Django 3.2.8 on 2021-10-12 08:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0002_car_showroom_sortquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_showroom',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2),
        ),
    ]
