# Generated by Django 3.2.8 on 2021-11-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0003_carsofshowroom_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowroom',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carsofshowroom',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
