# Generated by Django 3.2.8 on 2021-10-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0003_car_showroom_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_showroom',
            name='sortquery',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
