# Generated by Django 3.2.8 on 2021-11-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0006_auto_20211115_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsofshowroom',
            old_name='сar_showroom',
            new_name='car_showroom',
        ),
    ]
