# Generated by Django 3.2.8 on 2021-10-12 10:27

from django.db import migrations, models
import src.car_showroom.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0007_alter_car_showroom_sortquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_showroom',
            name='sortquery',
            field=models.JSONField(blank=True, default=src.car_showroom.models.jsonfield_default_value),
        ),
    ]
