# Generated by Django 3.2.8 on 2021-11-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0007_rename_сar_showroom_carsofshowroom_car_showroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showroomsale',
            old_name='showroom',
            new_name='car_showroom',
        ),
    ]
