# Generated by Django 3.2.8 on 2021-10-13 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0008_alter_car_showroom_sortquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_showroom_car',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
