# Generated by Django 3.2.8 on 2021-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_showroom', '0009_alter_car_showroom_car_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_showroom',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car_showroom_car',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
