# Generated by Django 3.2.8 on 2021-11-10 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.tools.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('width', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('mileage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', src.tools.fields.DecimalRangeField(decimal_places=2, max_digits=10, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default='1900', validators=[django.core.validators.MaxValueValidator(2021)])),
                ('color', models.CharField(blank=True, choices=[('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('BLACK', 'Black'), ('WHITE', 'White'), ('GRAY', 'Gray')], default='white', max_length=200)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-HJ-NPR-Za-hj-npr-z\\d]{8}[\\dX][A-HJ-NPR-Za-hj-npr-z\\d]{2}\\d{6}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('balance', src.tools.fields.DecimalRangeField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('discount', src.tools.fields.DecimalRangeField(decimal_places=2, default=1, max_digits=10)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', related_query_name='supplier', to='supplier.car', to_field='vin')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_cars', related_query_name='supplier_car', to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='cars',
            field=models.ManyToManyField(through='supplier.SupplierCar', to='supplier.Car'),
        ),
    ]
