# Generated by Django 3.2.8 on 2021-11-12 09:05

from django.db import migrations, models
import django.db.models.deletion
import src.tools.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('BLACK', 'Black'), ('WHITE', 'White'), ('GRAY', 'Gray')], default='white', max_length=7),
        ),
        migrations.CreateModel(
            name='SupplierSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount', src.tools.fields.DecimalRangeField(decimal_places=2, default=1, max_digits=10)),
                ('end_date', models.DateField(blank=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_sale', related_query_name='car_sale', to='supplier.car', to_field='vin')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sale', related_query_name='supplier_sale', to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
