# Generated by Django 3.2.8 on 2021-10-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_car',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.car', to_field='vin'),
        ),
    ]
