# Generated by Django 3.2.8 on 2021-11-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20211112_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suppliercar',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suppliersale',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
