# Generated by Django 3.2.8 on 2021-10-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20211022_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='car',
            new_name='cars',
        ),
    ]
